// selector arrays
export const genusList = [
    'Aeschynomene',
    'Arachis',
    'Cajanus',
    'Cercis',
    'Cicer',
    'Glycine',
    'Lens',
    'Lotus',
    'Lupinus',
    'Medicago',
    'Phaseolus',
    'Pisum',
    'Trifolium',
    'Vigna'
];

export const speciesList = {
    'Aeschynomene': ['evenia'],
    'Arachis': ['cardenasii',
                'duranensis',
                'hypogaea',
                'ipaensis',
                'stenosperma'],
    'Cajanus':  ['cajan'],
    'Cercis': ['canadensis'],
    'Cicer': [
        'arietinum',
        'echinospermum',
        'reticulatum'],
    'Glycine': ['D3-tomentella',
                'cyrtoloba',
                'dolichocarpa',
                'falcata',
                'max',
                'soja',
                'stenophita',
                'syndetika'],
    'Lens': ['culinaris',
             'ervoides'],
    'Lotus': ['japonicus'],
    'Lupinus': ['albus',
                'angustifolius'],
    'Medicago': ['polymorpha',
                 'ruthenica',
                 'sativa',
                 'truncatula'],
    'Phaseolus': ['acutifolius',
                  'lunatus',
                  'vulgaris'],
    'Pisum': ['sativum'],
    'Trifolium': ['pratense',
                  'subterraneum'],
    'Vigna': ['angularis',
              'radiata',
              'unguiculata']
}

export const strainList = {
    'D3-tomentella': ['G1403'],
    'acutifolius': ['Frijol_Bayo',
                    'W6_15578'],
    'albus': ['Amiga'],
    'angularis':  ['Gyeongwon',
                   'Shumari'],
    'angustifolius': ['Tanjil'],
    'arietinum': ['CDCFrontier',
                  'ICC4958'],
    'cajan': ['ICPL87119'],
    'canadensis': ['ISC453364'],
    'culinaris': ['CDC_Redberry'],
    'cyrtoloba': ['G1267'],
    'dolichocarpa': ['G1134'],
    'duranensis': ['V14167'],
    'echinospermum': ['S2Drd065'],
    'ervoides': ['IG_72815'],
    'evenia': ['CIAT22838'],
    'falcata': ['G1718'],
    'hypogaea': ['Tifrunner'],
    'ipaensis': ['K30076'],
    'japonicus': ['MG20'],
    'lunatus': ['G27455'],
    'max': ['58-161',
            'Amsoy',
            'DongNongNo_50',
            'FengDiHuang',
            'FiskebyIII',
            'HanDouNo_5',
            'Hefeng25_IGA1002',
            'HeiHeNo_43',
            'Huaxia3_IGA1007',
            'Hwangkeum',
            'JiDouNo_17',
            'JinDouNo_23',
            'Jinyuan_IGA1006',
            'JuXuanNo_23',
            'KeShanNo_1',
            'Lee',
            'PI_398296',
            'PI_548362',
            'QiHuangNo_34',
            'ShiShengChangYe',
            'TieFengNo_18',
            'TieJiaSiLiHuang',
            'TongShanTianEDan',
            'WanDouNo_28',
            'Wenfeng7_IGA1001',
            'Wm82',
            'Wm82_IGA1008',
            'Wm82_ISU01',
            'XuDouNo_1',
            'YuDouNo_22',
            'Zh13',
            'Zh13_IGA1005',
            'Zh35_IGA1004',
            'ZhangChunManCangJin',
            'Zhutwinning2',
            'ZiHuaNo_4'],
    'pratense': ['MilvusB'],
    'radiata': ['VC1973A'],
    'reticulatum': ['Besev079'],
    'sativa': ['XinJiangDaYe'],
    'sativum': ['Cameor'],
    'soja': ['F_IGA1003',
             'PI483463',
             'PI_549046',
             'PI_562565',
             'PI_578357',
             'W05'],
    'stenophita': ['G1974'],
    'subterraneum': ['Daliak'],
    'syndetika': ['G1300'],
    'truncatula': ['A17',
                   'A17_HM341',
                   'HM004',
                   'HM010',
                   'HM022',
                   'HM023',
                   'HM034',
                   'HM050',
                   'HM056',
                   'HM058',
                   'HM060',
                   'HM095',
                   'HM125',
                   'HM129',
                   'HM185',
                   'HM324',
                   'R108',
                   'R108_HM340'],
    'unguiculata': ['CB5-2',
                    'IT97K-499-35',
                    'Sanzi',
                    'Suvita2',
                    'TZ30',
                    'UCR779',
                    'Xiabao_II',
                    'ZN016'],
    'vulgaris':  ['5-593',
                  'G19833',
                  'LaborOvalle',
                  'UI111']
}
